apiVersion: v1
kind: ConfigMap
metadata:
  name: lanchonete-configmap
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/lanchonete_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
 
---
apiVersion: v1
kind: Secret
metadata:
  name: lanchonete-secret
data:
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-deployment
  labels:
    app: lanchonete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lanchonete
  template:
    metadata:
      labels:
        app: lanchonete
    spec:
      containers:
        - name: container-lanchonete
          image: piovezan1207/techchallenger-lanchonete-app:cleanv1.0.1
          ports:
            - containerPort: 8080
              protocol: TCP 
          envFrom:
            - configMapRef:
                name: lanchonete-configmap
            - secretRef:
                name: lanchonete-secret
          resources:
            requests:
              cpu: 40m

---
apiVersion: v1
kind: Service
metadata:
  name: svc-lanchonete
spec:
  type: NodePort
  ports: 
    - port: 80
      targetPort: 8080
      nodePort: 31300
  selector:
    app: lanchonete